esphome:
  name: sunton-70-test
  friendly_name: Sunton 7.0" Test

substitutions:
  home_page: lighting_1

packages:
  common: !include common.yaml
  device: !include devices/ESP32-8048S070.yaml
  layout: !include layouts/800x480.yaml
