# required vars:
# - uid
# - entity_id

sensor:
  - id: ${uid}_widget_sensor
    platform: homeassistant
    entity_id: ${entity_id}
    on_value:
      - lvgl.spinbox.update:
          id: ${uid}
          value: !lambda return x;

